name: Python CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем твой код
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Устанавливаем Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3. Устанавливаем зависимости (pip, pytest)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # 4. Запускаем тесты
      - name: Run tests
        run: pytest
